### ISSUE TITLE
Program hangs

### ISSUE THREAD

**Issue by thirstycrow** [DataDog/glommio#241] opened 2020-12-18 04:03 UTC
```rust
use glommio::{LocalExecutor, Local};

fn main() {
  LocalExecutor::make_default().run(async {
    Local::local(async { println!("hello") }).detach().await;

    // The program hangs if the following line is uncommented.
    // Local::local(async { println!("hello") }).detach().await;

    println!("world")
  });
}

```

**Comment by glommer** [comment] 2020-12-18 14:15
Ack, reproduced locally.

FWIW, this works:

```
fn main() {
  let ex = LocalExecutorBuilder::new().spawn(|| async {
    Local::local(async { println!("hello") }).detach().await;
    Local::local(async { println!("hello") }).detach().await;
    println!("world")
  }).unwrap();

  ex.join().unwrap();
}
```

Your code seems fine to me, but just a bit of reasoning and internals about what could be happening:
`run()` is special (I don't necessarily like that) because code you run in run (pun intended) doesn't belong to any task queue so there are things that you can't do (like yield). In your case you are spawning tasks and that should be fine. I have to investigate a bit more why this breaks.

But I also want to get rid of the special casing in `run()` as much as possible. It's very counter intuitive.

For the time being, in case you are blocked in your application, consider using a spawned executor as in the example I posted (which guarantees everything is inside a task queue). We'll handle this one.

Thanks!

**Comment by glommer** [comment] 2020-12-23 03:04
@thirstycrow this is fixed now.

Have a fantastic new year!

**Closed** 2020-12-23 03:03 UTC
Labels: bug
