### ISSUE TITLE
`StreamWriter` panics when `poll_write()` is called while a flush is happening

### ISSUE THREAD

**Issue by tontinton** [DataDog/glommio#594] opened 2023-03-26 20:33 UTC
I'm implementing a simple and stupid database, once I tried to benchmark it, I immediately crashed with the stacktrace that is written at the end of the post.

This is most likely a bug in glommio's StreamWriter, `poll_write()`
expects no writes while a flush is the current `self.source`.

The crash happens inside `consume_flush_result` where the
`source.result().unwrap()` panics because there is no result yet.

I took the description from my (I think) easy to understand commit: [dbil - 1bfe998](https://github.com/tontinton/dbil/commit/1bfe998eb45ec6e9e483a26db1fb03aec53c13bd), where you can see that putting the flush inside the "critical section" (the `is_wal_writing` flag), caused it to not panic anymore.

I'm also pretty sure that I can reproduce this without calling ever calling flush, as a flush might occur just by writing to the file.

I feel like this should not happen, but I might be wrong, it might be a design decision I missed somewhere in the docs.

Anyway, I really enjoy using the library, and would love to help resolve this if it is indeed an issue.

Stacktrace:

```
thread 'dbil-1' panicked at 'called `Option::unwrap()` on a `None` value', /home/tony/.cargo/registry/src/github.com-1ecc6299db9ec823/glommio-0.8.0
/src/io/buffered_file_stream.rs:376:19
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: glommio::io::buffered_file_stream::StreamWriter::consume_flush_result
   4: <glommio::io::buffered_file_stream::StreamWriter as futures_io::if_std::AsyncWrite>::poll_flush
   5: dbil::handle_request::{{closure}}
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: glommio::task::raw::RawTask<F,R,S>::run
   8: glommio::executor::LocalExecutor::run_task_queues
   9: scoped_tls::ScopedKey<T>::set
  10: glommio::executor::LocalExecutor::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: Custom { kind: Other, error: "Executor builder error: Executor builder error: thread panicked" }
```

**Comment by glommer** [comment] 2023-03-27 12:46
thanks @tontinton !
Is there a simple reproducer that you could share that I could trigger without running your full db? (ideally a glommio test that panics)

I have to go back and study the code again, as it's been a while since I last touched buffered files. Keep in mind that for DIO files, where I spend most of my time, because the files have strict alignment constraints, you are not supposed to flush and keep writing. Buffered files are different, and this could indeed be relaxed.

**Comment by glommer** [comment] 2023-03-27 12:52
thanks @tontinton !
Is there a simple reproducer that you could share that I could trigger without running your full db? (ideally a glommio test that panics)

I have to go back and study the code again, as it's been a while since I last touched buffered files. Keep in mind that for DIO files, where I spend most of my time, because the files have strict alignment constraints, you are not supposed to flush and keep writing. Buffered files are different, and this could indeed be relaxed.

**Comment by glommer** [comment] 2023-03-27 13:03
thanks @tontinton !
Is there a simple reproducer that you could share that I could trigger without running your full db? (ideally a glommio test that panics)

I have to go back and study the code again, as it's been a while since I last touched buffered files. Keep in mind that for DIO files, where I spend most of my time, because the files have strict alignment constraints, you are not supposed to flush and keep writing. Buffered files are different, and this could indeed be relaxed.

**Comment by glommer** [comment] 2023-03-27 13:11
The following patch seems to at least not break any existing tests:
```
diff --git a/glommio/src/io/buffered_file_stream.rs b/glommio/src/io/buffered_file_stream.rs
index f9d703e..be642e9 100644
--- a/glommio/src/io/buffered_file_stream.rs
+++ b/glommio/src/io/buffered_file_stream.rs
@@ -373,7 +373,11 @@ impl StreamWriter {
     }

     fn consume_flush_result(&mut self, source: Source) -> io::Result<()> {
-        let res = source.result().unwrap();
+        let res = match source.result() {
+            None => { return Ok(()); }
+            Some(x) => x,
+        };
+
         if res.is_ok() {
             if let IoBuffer::Buffered(mut buffer) = source.extract_buffer() {
                 self.file_pos += buffer.len() as u64;
```

I'd like to develop a bit more trust that this is the right thing to do. If it fix it for you, and we're able to have a test that used to panic fixed by this too, that'd be a great step

**Comment by tontinton** [comment] 2023-03-27 18:02
Hey, thanks for answering and I must say it's an honor :)

I've managed to reproduce with a simple yet ugly test case (would love to know if this can be reproduced without unsafes, as I call flush while calling write which both take self as `&mut`):

```rust
    write_test!(flush_and_write, path, _k, file, {
        let writer = Rc::new(UnsafeCell::new(StreamWriterBuilder::new(file).build()));

        unsafe {
            (*writer.get()).write_all(&[0, 1, 2, 3, 4]).await.unwrap();
        }

        let cloned_writer = writer.clone();
        spawn_local(async move {
            unsafe {
                (*cloned_writer.get())
                    .write_all(&[0, 1, 2, 3, 4])
                    .await
                    .unwrap();
            }
        })
        .detach();

        unsafe {
            (*writer.get()).flush().await.unwrap();
        }
        unsafe {
            (*writer.get()).close().await.unwrap();
        }
    });
```

And your code does seem to fix the panic, but I'm not 100% sure it's the correct behavior, the callers to `consume_flush_result` `take` the optional `self.source` and invalidate it to `None`, but maybe we want to reset `self.source` when it's not yet ready? idk, I'm not that into `glommio`'s internals yet.

Would love to hear your thoughts.

Thanks!

**Comment by glommer** [comment] 2023-03-28 19:49
Do you need concurrency for the bug to trigger?
The fact that you have to use unsafe is indeed a smell. For example, would it crash if you write + flush + write ?

I spent the day today taking a look at the code, and it seems to me that this could happen:
* poll_write gets called, there is data in the buffer, and we call `flush_write_buffer`.
* `flush_write_buffer` installs a source
* `poll_write` gets called again, before the `source` has a `result`.

So if that's the case, writing on a slow media in very quick succession could trigger it, maybe? It's not great when tests rely on characteristics of the media, but such is the life of I/O =p

The best thing to do, then, would be to check if the `source` has a result before invalidating it, and if it doesn't just reinstall and return pending. Would this also fix your crash? I can provide a patch that does that if you want.

**Comment by tontinton** [comment] 2023-04-01 08:59
Yeah that would fix the issue, although I'm currently moving to `DmaFile` anyway, maybe someone in the future might want that fix.

I do think though that if the bug is occurring only when concurrency is involved, then it's ok to also say that glommio doesn't support that.

**Closed** 2023-10-13 12:20 UTC
