### ISSUE TITLE
produce new docs + crates.io releases regularly

### ISSUE THREAD

**Issue by bryandmc** [DataDog/glommio#283] opened 2021-02-25 21:02 UTC
We should consider a mechanism to release Glommio more frequently.. Maybe this exists and I am just unaware, but I am updating the readme because I noticed something out of date and realized that the only version on crates.io is kinda old, or at least older than what is living in master right now. Obviously it'll become more important later to be more careful with releases (post 1.0) but right now we can probably release more frequently.

So maybe we should create a system to do the releases or at least host the docs somewhere. Does this already exist?

Thoughts?

**Comment by glommer** [comment] 2021-02-25 21:14
releasing while `iou` and `uring-sys` are git-based is an enormous manual pain in the ass process.
We use git for those because they depend on patches to liburing that are not on released versions (although they are. merged upstream).

Axboe has been promising me a new release for months now, and I know he's busy so this is kind of just slipping, which is why I keep delaying our update as well (although it's way past due).

This is starting to get on my nerves as well, because even if Axboe is to release today, there is no guarantee that `uring-sys` and `iou` would release right after so God knows how long this will take.

I am open to suggestions, but one thing we can do is just move the code for `uring-sys` and `iou` semi-permantly inside glommio. This would give us a bit more freedom to release, and if we're disciplined enough to always upstream patches first this is probably okay

**Comment by sehz** [comment] 2021-02-25 21:26
What about creating separate org for `glommio`  with `iou`.   Since Axboe doesn't seems to have time, the new org can maintain both repo and attract more developers?

**Comment by bryandmc** [comment] 2021-02-25 21:34
well Axboe would be involved in the underlying `liburing`, but your point about `iou` being forked and maintained by us is plausible and interesting..

Yeah this is all pretty complex and I see a number of different paths. I guess we have to determine if we think `uring-sys`/`iou` will ever start being maintained again, or not. If not, it might be a good idea to just fork it or see if he'll hand it over to us. @withoutboats was going to give the library he created (ringbahn i think?) to whoever wanted to maintain it. So maybe same goes for `iou`.

**Comment by glommer** [comment] 2021-02-25 21:38
@sehz Axboe maintains liburing, the C library. He's extremely active, and liburing gets a lot of developments and patches.
It's the releasing that has been slow. However that is not a big problem: if we controlled uring-sys, we could apply patches manually.

`iou` and `uring-sys` are indeed maintained by @withoutboats and are rust projects. He's been resistant in the past to merge liburing patches that are not in a release and I don't blame him.

Axboe promised me on twitter that he'd release last week. Let's give him some more time and see what happens

**Comment by sehz** [comment] 2021-02-25 21:50
There are now multiple implementations of  `io_uring`.   Any opinions on https://github.com/tokio-rs/io-uring which doesn't seems to have explicit dependencies to Tokio yet.

**Comment by glommer** [comment] 2021-02-25 21:54
io_uring is a very fast moving target in the kernel. And liburing is maintained by the same person who maintains the kernel. In that sense I view using liburing as a good thing, not something I want to avoid.

We should think about what to do with `iou` and `uring-sys`. Forking is always a last resort, but if we were to fork those the problem is gone: we wouldn't need to wait for liburing official releases, as we could always backport patches of interest.

**Comment by glommer** [comment] 2021-03-03 02:22
I just merged `iou` and `uring-sys` into glommio. We can release now.

I'd be slightly more comfortable with a released version of liburing, and Axboe and I are chatting on twitter about this - it should come really soon. I'll cut right after.

**Comment by glommer** [comment] 2021-03-05 03:27
Please consider reviewing the following:

https://github.com/DataDog/glommio/pull/291

I am cutting a release Sunday night (EST). If there is anything else you'd like to see in this release, let me know

**Comment by glommer** [comment] 2021-03-08 03:20
This is now done

**Closed by glommer** 2021-03-08 03:20 UTC
