### ISSUE TITLE
Sleep hangs when the sleep duration is very short

### ISSUE THREAD

**Issue by thirstycrow** [DataDog/glommio#326] opened 2021-04-15 05:24 UTC
The following test works on my laptop, but hangs while running on our virtual box for gitlab ci.

```rust
#[cfg(test)]
mod tests {
    use std::time::Duration;

    use glommio::prelude::*;
    use glommio::timer::sleep;

    #[test]
    fn test() {
        LocalExecutor::default().run(async {
            println!("begin");
            sleep(Duration::from_secs(1)).await;
            println!("here");
            sleep(Duration::from_millis(1)).await;  // It hangs here
            println!("end");
        });
    }
}
```

**Comment by glommer** [comment] 2021-04-15 13:10
Thanks Jiang

can you reproduce locally with microsecond-level sleeps ?

**Comment by glommer** [comment] 2021-04-15 23:16
I tried a couple of things locally, including running the tests concurrently with a `yes` call burning CPU and could not reproduce.

Could this be a kernel issue, maybe? 

In any case, it would be helpful if you could add some debug statements so we can figure out what's wrong.

A couple of interesting places:
* do we even register this timer into the reactor ? (that's done in `timer_impl.rs` and eventually calls `insert_timer`)
* if it gets registered, does the timer gets awaken by process_timers(), or is it registered into the `io_uring` ?
* if it goes through io_uring, does the cqe ever complete ?

**Comment by thirstycrow** [comment] 2021-04-16 07:06
I cannot reproduce with the pasted code today, but it still happen on a test in our application. I added some print statements in parking.rs and uring.rs. According to the output, the executor is sleeping in the main ring and never wake up again.

```
running 1 test
process external events before wait
processing timers: {}, now: Instant { tv_sec: 178989, tv_nsec: 375240497 }
   pending count: 0
   ready count: 0
waiting for the next timer: None
wait returns: false
timer registered with id: 1
timer (id: 1) inserted
processing timers: {(Instant { tv_sec: 178989, tv_nsec: 376478530 }, 1): Waker { data: 0x14f810026970, vtable: 0x561ea8a8bf58 }}, now: Instant { tv_sec: 178989, tv_nsec: 375566825 }
   pending count: 1
   ready count: 0
process external events before wait
processing timers: {(Instant { tv_sec: 178989, tv_nsec: 376478530 }, 1): Waker { data: 0x14f810026970, vtable: 0x561ea8a8bf58 }}, now: Instant { tv_sec: 178989, tv_nsec: 375630124 }
   pending count: 1
   ready count: 0
waiting for the next timer: Some(848.406µs)
set arm timer in the lat ring: 848.406µs
sleeping in the main ring
test dict::test::test_rehash ... test dict::test::test_rehash has been running for over 60 seconds
```

**Comment by glommer** [comment] 2021-04-16 13:48
Right, that the executor sleeps and doesn't wake up is predictable.
What is more interesting is finding out if this is because the timer never was registered, or because it never fired or never completed.

I don't know exactly where you put those prints -> care to elaborate?

But this suggests to me that we *did* register the timer:
```
set arm timer in the lat ring: 848.406µs
``` 
(I would like to understand exactly where we put this print)

I do have a theory: I think this is because the `Timeout` event is still special in the sleepable ring here:

```
    fn consume_one_event(&mut self, wakers: &mut Vec<Waker>) -> Option<()> {
        process_one_event(
            self.ring.peek_for_cqe(),
            |source| match &mut *source.source_type.borrow_mut() {
                SourceType::LinkRings => Some(()),
                SourceType::Timeout(_) => Some(()), <== because timers don't have external Source, this does not add anything to the wakers list, and we believe we can_sleep
                _ => None,
            },
            wakers,
        )
    }
```    

This code is very old and uring.rs is a lot more capable now. It can maybe be simplified. But it would be nice to know if this is the case. Maybe add a print there to confirm that this does fire, and that we go to sleep because we still thing that `wakers.len() == 0`.

**Comment by thirstycrow** [comment] 2021-04-17 14:41
I added print statements at the following places

```diff
diff --git a/glommio/src/parking.rs b/glommio/src/parking.rs
index 058aa02..08efe60 100644
--- a/glommio/src/parking.rs
+++ b/glommio/src/parking.rs
@@ -167,10 +167,12 @@ impl Timers {
 
     fn process_timers(&mut self, wakers: &mut Vec<Waker>) -> Option<Duration> {
         let now = Instant::now();
-
+        println!("processing {} timers", wakers.len());
         // Split timers into ready and pending timers.
         let pending = self.timers.split_off(&(now, 0));
+        println!("   pending count: {}", pending.len());
         let ready = mem::replace(&mut self.timers, pending);
+        println!("   ready count: {}", ready.len());
 
         // Calculate the duration until the next event.
         let dur = if ready.is_empty() {
@@ -572,7 +574,9 @@ impl Reactor {
     /// Returns the registered timer's ID.
     pub(crate) fn register_timer(&self) -> u64 {
         let mut timers = self.timers.borrow_mut();
-        timers.new_id()
+        let id = timers.new_id();
+        println!("timer registered with id: {}", id);
+        id
     }
 
     /// Registers a timer in the reactor.
@@ -581,6 +585,7 @@ impl Reactor {
     pub(crate) fn insert_timer(&self, id: u64, when: Instant, waker: Waker) {
         let mut timers = self.timers.borrow_mut();
         timers.insert(id, when, waker);
+        println!("timer (id: {}) inserted", id);
     }
 
     /// Deregisters a timer from the reactor.
diff --git a/glommio/src/sys/uring.rs b/glommio/src/sys/uring.rs
index d77a11a..d76ebbe 100644
--- a/glommio/src/sys/uring.rs
+++ b/glommio/src/sys/uring.rs
@@ -987,10 +987,13 @@ impl UringCommon for SleepableRing {
     fn consume_one_event(&mut self, wakers: &mut Vec<Waker>) -> Option<()> {
         process_one_event(
             self.ring.peek_for_cqe(),
-            |source| match &mut *source.source_type.borrow_mut() {
-                SourceType::LinkRings => Some(()),
-                SourceType::Timeout(_) => Some(()),
-                _ => None,
+            |source| {
+                println!("An event of type {:?} is fired", source.source_type.borrow());
+                match &mut *source.source_type.borrow_mut() {
+                    SourceType::LinkRings => Some(()),
+                    SourceType::Timeout(_) => Some(()),
+                    _ => None,
+                }
             },
             wakers,
         )
@@ -1329,8 +1332,10 @@ impl Reactor {
             self.link_fd,
             SourceType::LinkRings,
         );
+        println!("sleep in the main ring");
         ring.sleep(&mut link_rings, eventfd_src)
             .or_else(Self::busy_ok)?;
+        println!("waken");
         Ok(())
     }
 
@@ -1434,6 +1439,7 @@ impl Reactor {
             // We are about to go to sleep. It's ok to sleep, but if there
             // is a timer set, we need to make sure we wake up to handle it.
             if let Some(dur) = user_timer {
+                println!("set arm timer in the lat ring: {:?}", dur.clone());
                 self.timeout_src.set(Some(lat_ring.arm_timer(dur)));
                 flush_rings!(lat_ring)?;
             }
```

It produces output like this:
```
running 1 test
processing 0 timers
   pending count: 0
   ready count: 0
timer registered with id: 1
timer (id: 1) inserted
processing 0 timers
   pending count: 1
   ready count: 0
processing 0 timers
   pending count: 1
   ready count: 0
An event of type Timeout(100ms) is fired  ??? Where does this timeout come from?
set arm timer in the lat ring: 816.819µs
sleep in the main ring
test dict::test::test_rehash ... test dict::test::test_rehash has been running for over 60 seconds
```

**Comment by glommer** [comment] 2021-04-19 15:16
```
An event of type Timeout(100ms) is fired  ??? Where does this timeout come from? There's only one sleep with a timeout of 1ms in the code
``` <== This is the preempt timer, which fires at every 100ms to make `need_preempt()` become true, which results in the reactor yielding to other tasks in the system.

Let's check a couple of other things:
1. Which kernel are you running on that CI ?
2. Let's verify which ID is being assigned to the timer. It it inside `arm_timer`, and it is the result of `to_user_data(new_id)`
3. is `fill_sqe` called for that id ? and is that a timer request? (the id is `op.user_data`)
4. Inside `fn sleep(...) -> io::Result`, which branches do we take? Let's add one print per branch
5. Do any call to `submit_sqes` or `submit_sqes_and_wait` return an error? Maybe we don't see the wake because we error out, and the error is not correctly handled.

**Comment by thirstycrow** [comment] 2021-04-21 03:03
The kernel version is 5.11.13-1.el7.elrepo.x86_64. 

Everything seems work fine, except that `submit_sqes_and_wait` does not return:

<pre>
running 1 test
fill_sqe: user_data: 1, args: Read(0, 8)
processing 0 timers
   pending count: 0
   ready count: 0
arm_timer: 100ms, new_id: Idx { raw: 1, _ty: PhantomData }, user_data: 2
calling uring_sys::io_uring_submit
uring_sys::io_uring_submit returned 1
fill_sqe: user_data: 2, args: Timeout(0x150acc026b00)
calling uring_sys::io_uring_submit
uring_sys::io_uring_submit returned 1
timer registered with id: 1
timer (id: 1) inserted
processing 0 timers
   pending count: 1
   ready count: 0
processing 0 timers
   pending count: 1
   ready count: 0
fill_sqe: user_data: 0, args: Cancel(2)
calling uring_sys::io_uring_submit
uring_sys::io_uring_submit returned 1
set arm timer in the lat ring: 764.806µs
<b>arm_timer: 764.806µs, new_id: Idx { raw: 1, _ty: PhantomData }, user_data: 2</b>
<b>fill_sqe: user_data: 2, args: Timeout(0x150acc026b00)</b>
calling uring_sys::io_uring_submit
uring_sys::io_uring_submit returned 1
sleep in the main ring
<b>In fn sleep(...): self.ring.prepare_sqe() returned Some(_)</b>
fill_sqe: user_data: 3, args: PollAdd(POLLIN | POLLPRI | POLLERR | POLLHUP | POLLNVAL)
<b>In fn sleep(...): eventfd_src.take_result() returned None</b>
calling uring_sys::io_uring_submit_and_wait
</pre>

```diff
diff --git a/glommio/src/iou/submission_queue.rs b/glommio/src/iou/submission_queue.rs
index 9972929..bff06e0 100644
--- a/glommio/src/iou/submission_queue.rs
+++ b/glommio/src/iou/submission_queue.rs
@@ -52,11 +52,18 @@ impl<'ring> SubmissionQueue<'ring> {
     /// If this function encounters any IO errors an
     /// [`io::Error`](std::io::Result) variant is returned.
     pub fn submit(&mut self) -> io::Result<u32> {
-        resultify(unsafe { uring_sys::io_uring_submit(self.ring.as_ptr()) })
+        println!("calling uring_sys::io_uring_submit");
+        let result = unsafe { uring_sys::io_uring_submit(self.ring.as_ptr()) };
+        println!("uring_sys::io_uring_submit returned {}", result);
+        resultify(result)
     }
 
     pub fn submit_and_wait(&mut self, wait_for: u32) -> io::Result<u32> {
-        resultify(unsafe { uring_sys::io_uring_submit_and_wait(self.ring.as_ptr(), wait_for as _) })
+        println!("calling uring_sys::io_uring_submit_and_wait");
+        let result =
+            unsafe { uring_sys::io_uring_submit_and_wait(self.ring.as_ptr(), wait_for as _) };
+        println!("uring_sys::io_uring_submit_and_wait returned {}", result);
+        resultify(result)
     }
 
     pub fn submit_and_wait_with_timeout(
diff --git a/glommio/src/sys/uring.rs b/glommio/src/sys/uring.rs
index 284ad4c..bdd431e 100644
--- a/glommio/src/sys/uring.rs
+++ b/glommio/src/sys/uring.rs
@@ -269,6 +269,7 @@ where
     F: FnOnce(usize) -> Option<DmaBuffer>,
 {
     let mut user_data = op.user_data;
+    println!("fill_sqe: user_data: {}, args: {:?}", user_data, op.args);
     unsafe {
         match op.args {
             UringOpDescriptor::PollAdd(events) => {
@@ -876,7 +877,7 @@ impl SleepableRing {
         let source = Source::new(
             IoRequirements::default(),
             -1,
-            SourceType::Timeout(TimeSpec64::from(d)),
+            SourceType::Timeout(TimeSpec64::from(d.clone())),
         );
         let new_id = add_source(&source, self.submission_queue.clone());
         let op = match &*source.source_type() {
@@ -889,11 +890,13 @@ impl SleepableRing {
         // and is processed inline there is no need to link sqes.
         let q = self.submission_queue();
         let mut queue = q.borrow_mut();
+        let user_data = to_user_data(new_id);
+        println!("arm_timer: {:?}, new_id: {:?}, user_data: {}", d, new_id, user_data);
         queue.submissions.push_front(UringDescriptor {
             args: op,
             fd: -1,
             flags: SubmissionFlags::empty(),
-            user_data: to_user_data(new_id),
+            user_data,
         });
         // No need to submit, the next ring enter will submit for us. Because
         // we just flushed and we got put in front of the queue we should get a SQE.
@@ -922,6 +925,7 @@ impl SleepableRing {
 
     fn sleep(&mut self, link: &mut Source, eventfd_src: &Source) -> io::Result<usize> {
         if let Some(mut sqe) = self.ring.prepare_sqe() {
+            println!("In fn sleep(...): self.ring.prepare_sqe() returned Some(_)");
             self.waiting_submission += 1;
 
             let op = UringDescriptor {
@@ -932,6 +936,7 @@ impl SleepableRing {
             };
             fill_sqe(&mut sqe, &op, DmaBuffer::new);
         } else {
+            println!("In fn sleep(...): self.ring.prepare_sqe() returned None");
             // Can't link rings because we ran out of CQEs. Just can't sleep.
             // Submit what we have, once we're out of here we'll consume them
             // and at some point will be able to sleep again.
@@ -941,11 +946,13 @@ impl SleepableRing {
         let res = eventfd_src.take_result();
         match res {
             None => {
+                println!("In fn sleep(...): eventfd_src.take_result() returned None");
                 // We already have the eventfd registered and nobody woke us up so far.
                 // Just proceed to sleep
                 self.ring.submit_sqes_and_wait(1).map(|x| x as usize)
             }
             Some(res) => {
+                println!("In fn sleep(...): eventfd_src.take_result() returned Some");
                 if self.install_eventfd(eventfd_src) {
                     // Do not expect any failures reading from eventfd. This will panic if we
                     // failed.
```

**Comment by glommer** [comment] 2021-04-21 11:50
I can't see how this is not a kernel bug.
I will try to work on a simpler reproducer. But we prepared the sqes, successfully called io_uring_submit, and yet the timer doesn't fire.

**Comment by thirstycrow** [comment] 2021-08-23 07:14
Upgraded kernel to the latest mainline (5.13.12) from the ELRepo, sleeping now also hangs on our CentOS 7.6 production servers. 
However it works well with the 5.13.12 kernel on my Ubuntu 20.04 laptop.

After some experiments, I found a fix by setting the POLL_BUSY_LOOP bit when preparing the PollAdd operation for ring linking.
I don't find any documentation on what kind of events would be fired when polling a ring where a timeout operation is ready. But shouldn't that be definite? @glommer 

```diff
--- a/glommio/src/iou/sqe.rs
+++ b/glommio/src/iou/sqe.rs
@@ -343,7 +343,7 @@ impl<'a> SQE<'a> {
 
     #[inline]
     pub unsafe fn prep_poll_add(&mut self, fd: impl UringFd, poll_flags: PollFlags) {
-        uring_sys::io_uring_prep_poll_add(self.sqe, fd.as_raw_fd(), poll_flags.bits());
+        uring_sys::io_uring_prep_poll_add(self.sqe, fd.as_raw_fd(), poll_flags.bits() | (1 << 15));
         fd.update_sqe(self);
     }
```

**Comment by glommer** [comment] 2021-08-23 20:54
I will have to read up on what the flag does.
If it does what the name implies, then it is not an acceptable fix (although a direction about what could be wrong)

**Comment by glommer** [comment] 2021-08-23 21:18
I am running on 5.14 now and I just tried your reproducer a couple of times. It still passes every time

**Closed** 2022-01-06 14:20 UTC
Labels: potential problem
